name: CI/CD Pipeline

on:
  push:
    branches: [staging]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Deploy to EC2
        run: echo "Deploy step here"